/**
 * Pure HTML builder for the shareable PDF export. NO react-native imports — the screen assembles
 * a `ReportData` from the same `lib/reports.ts` aggregates it renders on-screen and hands it here,
 * so the PDF and the dashboard always show identical numbers. `expo-print` turns the returned
 * string into a PDF (`app/(tabs)/reports.tsx`).
 */

export interface ReportRow {
  label: string;
  value: string;
  /** Optional muted note shown after the label (e.g. a brand or streak). */
  note?: string;
}

export interface ReportSection {
  title: string;
  rows: ReportRow[];
  /** Shown instead of rows when the section has no data. */
  empty?: string;
}

export interface ReportData {
  periodLabel: string; // "Last 30 days"
  dateRange: string; // "Aug 9 – Sep 8, 2026"
  headline: string;
  sections: ReportSection[];
}

const BRAND = '#2F9E44';
const INK = '#16241A';
const INK2 = '#5B6B5E';
const HAIR = '#E3EADD';
const PAPER = '#F6F8F3';

/** Escape user-supplied text (food/brand/meal names) for safe HTML embedding. */
function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string
  );
}

function sectionHtml(s: ReportSection): string {
  const body =
    s.rows.length === 0
      ? `<p class="empty">${esc(s.empty ?? 'No data for this period.')}</p>`
      : s.rows
          .map(
            (r) => `<div class="row">
              <span class="row-label">${esc(r.label)}${r.note ? `<span class="note"> ${esc(r.note)}</span>` : ''}</span>
              <span class="row-value">${esc(r.value)}</span>
            </div>`
          )
          .join('');
  return `<section><h2>${esc(s.title)}</h2>${body}</section>`;
}

export function buildReportHtml(d: ReportData): string {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 32px 28px 40px;
    font-family: -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    color: ${INK}; background: ${PAPER}; -webkit-print-color-adjust: exact; print-color-adjust: exact;
  }
  .kicker { font-size: 11px; letter-spacing: .12em; text-transform: uppercase; color: ${BRAND}; font-weight: 700; margin: 0 0 4px; }
  h1 { font-size: 30px; margin: 0 0 2px; letter-spacing: -.01em; }
  .range { color: ${INK2}; font-size: 13px; margin: 0 0 18px; }
  .headline {
    background: linear-gradient(120deg, #EAF7EC 0%, #F6FBF3 100%);
    border: 1px solid ${HAIR}; border-radius: 16px; padding: 14px 16px; margin: 0 0 22px;
    font-size: 15px; font-weight: 600; color: #1B5E2A;
  }
  section { margin: 0 0 20px; page-break-inside: avoid; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: .06em; color: ${INK2}; margin: 0 0 8px; border-bottom: 1px solid ${HAIR}; padding-bottom: 6px; }
  .row { display: flex; justify-content: space-between; align-items: baseline; padding: 5px 0; font-size: 13.5px; }
  .row + .row { border-top: 1px solid #F0F3EC; }
  .row-label { color: ${INK}; font-weight: 500; }
  .note { color: #8B9A8D; font-weight: 400; font-size: 12px; }
  .row-value { color: ${INK}; font-weight: 700; white-space: nowrap; padding-left: 12px; }
  .empty { color: #8B9A8D; font-size: 12.5px; margin: 4px 0; }
  footer { margin-top: 26px; color: #9AA79B; font-size: 11px; text-align: center; }
</style>
</head>
<body>
  <p class="kicker">NutriCraft Insights</p>
  <h1>${esc(d.periodLabel)}</h1>
  <p class="range">${esc(d.dateRange)}</p>
  <div class="headline">${esc(d.headline)}</div>
  ${d.sections.map(sectionHtml).join('')}
  <footer>Generated by NutriCraft · local-first nutrition &amp; price tracker</footer>
</body>
</html>`;
}
